version: "3.8"
services:
    ####################################################################################################
    # Creating container MySQL
    ####################################################################################################
    mysql:
        image: mariadb:10.4.13
        ports:
           - '3306:3306'
        volumes:
            - ./image/mysql/data/:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=aqwe123
        restart: always

    ####################################################################################################
    # Creating container PHP
    ####################################################################################################
    php:
        build: ./image/php/
        ports:
            - "9000:9000"
        volumes:
            - ./www/lumen/:/var/www/html
            
        links:
            - mysql

    ####################################################################################################
    # Creating container (Nginx)
    ####################################################################################################
    nginx:
        image: nginx:1.18.0
        ports:
            - 8080:80
        volumes:
            - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./www/lumen/public:/var/www/html/public
            - ./www/lumen/public/images:/var/www/html/public/images
            
        depends_on:
            - php
